-- Creabase_Nolark.sql
-- Script de création de la base de données (MySQL) du site nolark
-- Host: localhost          Database: NOLARK
-- ----------------------------------------------------------------
-- Fait par Nassim AHMED ALI et Luke DUSSART 

DROP DATABASE IF EXISTS NOLARK;
CREATE DATABASE IF NOT EXISTS NOLARK;
USE NOLARK;

DROP TABLE IF EXISTS `MEMBRES`;
DROP TABLE IF EXISTS `ARTICLES`;
DROP TABLE IF EXISTS `COMMANDES`;

CREATE TABLE `MEMBRES`
(
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PSEUDO` VARCHAR(20) NOT NULL,
    `PWD` VARCHAR(20) NOT NULL,
    `PRENOM` VARCHAR(20),
    `NOM` VARCHAR(20),
    `ADRESSE` VARCHAR(20),
	`MAIL` VARCHAR(30),
    `DATE_INSCRIT` TIMESTAMP NOT NULL default CURRENT_TIMESTAMP,
    CONSTRAINT PK_MEMBRES PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ARTICLES`
(
    `ID` INTEGER NOT NULL,
    `NOM` VARCHAR(20) NOT NULL,
    `DESCRIPTION` VARCHAR(20) NOT NULL,
    `CATEGORIE` VARCHAR(20) NOT NULL,
    `PRIX` DECIMAL NOT NULL,
    `STOCK` INTEGER NOT NULL,
    CONSTRAINT PK_ARTICLES PRIMARY KEY(ID),
    CONSTRAINT CKC_ARTICLES_PRIX CHECK(PRIX > 0),
    CONSTRAINT CKC_ARTICLES_STOCK CHECK(STOCK >= 0)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `COMMANDES`
(
    `IDMEMBRE` INTEGER NOT NULL,
    `IDARTICLE` INTEGER NOT NULL,
    CONSTRAINT PK_COMMANDES PRIMARY KEY(IDMEMBRE,IDARTICLE),
    CONSTRAINT FK_MEMBRE_COMMANDE_IDMEMBRE FOREIGN KEY(IDMEMBRE)
        REFERENCES MEMBRES(ID),
    CONSTRAINT FK_MEMBRE_COMMANDE_IDARTICLE FOREIGN KEY(IDARTICLE)
        REFERENCES ARTICLES(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
